name: go-integration-minio
services:
  go-integration-minio:
    container_name: go-integration-minio
    restart: unless-stopped
    build:
      context: .
      dockerfile: debug/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: go run cmd/app/main.go
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - minio
    networks:
      - go-network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

volumes:
  minio_data: